### ISSUE TITLE
can not find property with name 'id'; nested exception is com.fasterxml.jackson.databind.JsonMappingException: Invalid Object Id definition for node entity

### ISSUE THREAD

**Issue by cloudhuang** [neo4j-examples/movies-java-spring-data-neo4j#20] opened 2017-09-30 07:29 UTC
Here, I try to implement the same relationship between company and person, but when involve the spring data rest, I get the following error message finally, seems spring data rest will modify the bean properties to serialize to JSON. ( See com.fasterxml.jackson.databind.ser.BeanSerializerFactory#constructBeanSerializer )

```
[
    "org.springframework.hateoas.VndErrors",
    [
        {
            "@class":"org.springframework.hateoas.VndErrors$VndError",
            "logref":"HttpMessageNotWritableException",
            "message":"Could not write JSON: Invalid Object Id definition for com.example.graph.domain.Company: can not find property with name 'id'; nested exception is com.fasterxml.jackson.databind.JsonMappingException: Invalid Object Id definition for com.example.graph.domain.Company: can not find property with name 'id' (through reference chain: org.springframework.hateoas.PagedResources["_embedded"]->java.util.Collections$UnmodifiableMap["companies"]->java.util.ArrayList[0])",
            "links":[
                "java.util.ArrayList",
                [

                ]
            ]
        }
    ]
]
```

### Company.java
```
@Data
@NoArgsConstructor
@AllArgsConstructor
@ToString
@NodeEntity(label = "Company")
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
public class Company {
    /**
     * Graph ID
     */
    @GraphId
    private Long id;
    ......
}
```

### CompanyRepository.java
```
@RepositoryRestResource(collectionResourceRel = "companies", path = "companies")
public interface CompanyRepository extends PagingAndSortingRepository<Company, Long> {
}

```

**Comment by dwhitla** [comment] 2018-01-03 02:37
I suspect this is because your **id** field is identified by spring-data-rest as an id property and it hasn't been marked as exposed for serialization.

See org.springframework.data.rest.webmvc.json.PersistentEntityJackson2Module.changeProperties() for details. Towards the bottom of that method you will see something like this ...
`
if (persistentProperty.isIdProperty() && !associations.isIdExposed(entity)) {
    continue;
}
`
which is filtering your **id** attribute out of the list of bean properties available for the BeanSerializer to use when looking up your JSON identity property.

You can probably work around this using RepositoryRestConfiguration.exposeIdsFor(Class<?>... domainTypes).

**Comment by michael-simons** [comment] 2020-10-06 11:38
Closing this, seems to be more of a question and not an issue with the code here.

**Closed as completed by michael-simons** 2020-10-06 11:38 UTC

**Comment by dwhitla** [comment] 2020-10-06 11:42
The issue is relying on _magic_ field names in frameworks. Don't do it. Using annotations instead and give the user of the framework the ability to configure around your assumptions.
