### ISSUE TITLE
Examples do not seem to work

### ISSUE THREAD

**Issue by arafalov** [neo4j-examples/movies-java-spring-data-neo4j#3] opened 2016-05-12 01:17 UTC
Building (in IntelliJ) as per instructions with no changes. Then, running endpoints end-up with errors:

```
$ curl http://localhost:8080/movies/search/findByTitle?title=The%20Matrix
{
  "@id" : "1",
  "title" : "The Matrix",
  "released" : 1999,
  "tagline" : "Welcome to the Real World",
  "roles" : [ {
    "@id" : "2",
    "roles" : [ "Emil" ],
    "person" : {
      "@id" : "3"{
  "timestamp" : "2016-05-12T01:13:04.109+0000",
  "status" : 200,
  "error" : "OK",
  "exception" : "org.springframework.http.converter.HttpMessageNotWritableException",
  "message" : "Could not write content: Can not start an object, expecting field name; nested exception is com.fasterxml.jackson.core.JsonGenerationException: Can not start an object, expecting field name",
  "path" : "/movies/search/findByTitle"
}
```

```
$ curl http://localhost:8080/graph
{
  "timestamp" : "2016-05-12T01:15:43.698+0000",
  "status" : 500,
  "error" : "Internal Server Error",
  "exception" : "java.lang.ClassCastException",
  "message" : "[Ljava.lang.String; cannot be cast to java.util.Collection",
  "path" : "/graph"
}
```

The exception for the last one:

```
java.lang.ClassCastException: [Ljava.lang.String; cannot be cast to java.util.Collection
    at movies.spring.data.neo4j.services.MovieService.toD3Format(MovieService.java:26) ~[classes/:na]
    at movies.spring.data.neo4j.services.MovieService.graph(MovieService.java:48) ~[classes/:na]
    at movies.spring.data.neo4j.services.MovieService$$FastClassBySpringCGLIB$$e4763147.invoke(<generated>) ~[classes/:na]
    at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.2.3.RELEASE.jar:4.2.3.RELEASE]
    at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:718) ~[spring-aop-4.2.3.RELEASE.jar:4.2.3.RELEASE]
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) ~[spring-aop-4.2.3.RELEASE.jar:4.2.3.RELEASE]
    at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99) ~[spring-tx-4.2.3.RELEASE.jar:4.2.3.RELEASE]
    at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281) ~[spring-tx-4.2.3.RELEASE.jar:4.2.3.RELEASE]
    at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96) ~[spring-tx-4.2.3.RELEASE.jar:4.2.3.RELEASE]
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.2.3.RELEASE.jar:4.2.3.RELEASE]
    at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:654) ~[spring-aop-4.2.3.RELEASE.jar:4.2.3.RELEASE]
    at movies.spring.data.neo4j.services.MovieService$$EnhancerBySpringCGLIB$$22e35b7.graph(<generated>) ~[classes/:na]
    at movies.spring.data.neo4j.SampleMovieApplication.graph(SampleMovieApplication.java:34) ~[classes/:na]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_31]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_31]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_31]
    at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_31]
    at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:222) ~[spring-web-4.2.3.RELEASE.jar:4.2.3.RELEASE]
    at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137) ~[spring-web-4.2.3.RELEASE.jar:4.2.3.RELEASE]
    at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110) ~[spring-webmvc-4.2.3.RELEASE.jar:4.2.3.RELEASE]
    at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:814) ~[spring-webmvc-4.2.3.RELEASE.jar:4.2.3.RELEASE]
    at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:737) ~[spring-webmvc-4.2.3.RELEASE.jar:4.2.3.RELEASE]
    at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85) ~[spring-webmvc-4.2.3.RELEASE.jar:4.2.3.RELEASE]
    at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959) ~[spring-webmvc-4.2.3.RELEASE.jar:4.2.3.RELEASE]
    at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893) ~[spring-webmvc-4.2.3.RELEASE.jar:4.2.3.RELEASE]
    at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970) ~[spring-webmvc-4.2.3.RELEASE.jar:4.2.3.RELEASE]
    at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861) ~[spring-webmvc-4.2.3.RELEASE.jar:4.2.3.RELEASE]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:622) ~[tomcat-embed-core-8.0.28.jar:8.0.28]
    at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846) ~[spring-webmvc-4.2.3.RELEASE.jar:4.2.3.RELEASE]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:729) ~[tomcat-embed-core-8.0.28.jar:8.0.28]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291) ~[tomcat-embed-core-8.0.28.jar:8.0.28]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) ~[tomcat-embed-core-8.0.28.jar:8.0.28]
    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) ~[tomcat-embed-websocket-8.0.28.jar:8.0.28]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) ~[tomcat-embed-core-8.0.28.jar:8.0.28]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) ~[tomcat-embed-core-8.0.28.jar:8.0.28]
    at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99) ~[spring-web-4.2.3.RELEASE.jar:4.2.3.RELEASE]
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.2.3.RELEASE.jar:4.2.3.RELEASE]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) ~[tomcat-embed-core-8.0.28.jar:8.0.28]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) ~[tomcat-embed-core-8.0.28.jar:8.0.28]
    at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:87) ~[spring-web-4.2.3.RELEASE.jar:4.2.3.RELEASE]
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.2.3.RELEASE.jar:4.2.3.RELEASE]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) ~[tomcat-embed-core-8.0.28.jar:8.0.28]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) ~[tomcat-embed-core-8.0.28.jar:8.0.28]
    at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:77) ~[spring-web-4.2.3.RELEASE.jar:4.2.3.RELEASE]
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.2.3.RELEASE.jar:4.2.3.RELEASE]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) ~[tomcat-embed-core-8.0.28.jar:8.0.28]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) ~[tomcat-embed-core-8.0.28.jar:8.0.28]
    at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:121) ~[spring-web-4.2.3.RELEASE.jar:4.2.3.RELEASE]
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.2.3.RELEASE.jar:4.2.3.RELEASE]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) ~[tomcat-embed-core-8.0.28.jar:8.0.28]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) ~[tomcat-embed-core-8.0.28.jar:8.0.28]
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:217) ~[tomcat-embed-core-8.0.28.jar:8.0.28]
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) [tomcat-embed-core-8.0.28.jar:8.0.28]
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502) [tomcat-embed-core-8.0.28.jar:8.0.28]
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142) [tomcat-embed-core-8.0.28.jar:8.0.28]
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [tomcat-embed-core-8.0.28.jar:8.0.28]
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [tomcat-embed-core-8.0.28.jar:8.0.28]
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518) [tomcat-embed-core-8.0.28.jar:8.0.28]
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091) [tomcat-embed-core-8.0.28.jar:8.0.28]
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:673) [tomcat-embed-core-8.0.28.jar:8.0.28]
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500) [tomcat-embed-core-8.0.28.jar:8.0.28]
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456) [tomcat-embed-core-8.0.28.jar:8.0.28]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_31]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_31]
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.0.28.jar:8.0.28]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_31]
```

**Comment by luanne** [comment] 2016-05-12 03:55
Which version of Neo4j are you using?

**Comment by arafalov** [comment] 2016-05-12 04:01
Latest. Version 3.

**Comment by luanne** [comment] 2016-05-12 04:06
Right, 4.1.1.RELEASE is not compatible with Neo4j 3. The examples will work with Neo4j 2.x
If you'd like to use Neo4j 3, please change the SDN version to 4.2.0.BUILD-SNAPSHOT

**Comment by arafalov** [comment] 2016-05-12 04:07
Thanks. I'll check and confirm.

**Comment by arafalov** [comment] 2016-05-12 06:43
I've changed the pom to say:
`<spring-data-neo4j.version>4.2.0.BUILD-SNAPSHOT</spring-data-neo4j.version>`

It stopped compiling:

> [ERROR] Failed to execute goal on project movies-java-spring-data-neo4j-4: Could not resolve dependencies for project sample:movies-java-spring-data-neo4j-4:jar:1.0-SNAPSHOT: The following artifacts could not be resolved: org.neo4j:neo4j-ogm-core:jar:2.0.2-SNAPSHOT, org.neo4j:neo4j-ogm-http-driver:jar:2.0.2-SNAPSHOT: Could not find artifact org.neo4j:neo4j-ogm-core:jar:2.0.2-SNAPSHOT in spring-milestones (http://repo.spring.io/libs-snapshot) -> [Help 1]

I downloaded that one from GitHub and did 'mvn install' and this project now compiled again but gives the same error I opened the case with:

```
$ curl http://localhost:8080/graph
{
  "timestamp" : "2016-05-12T06:41:28.066+0000",
  "status" : 500,
  "error" : "Internal Server Error",
  "exception" : "java.lang.ClassCastException",
  "message" : "[Ljava.lang.String; cannot be cast to java.util.Collection",
  "path" : "/graph"
}
```

I am getting the same result. In fact, in the exception trace, there is no spring-data-neo4j in the stack at all. The problem seems to be in more core layer possible.

**Comment by luanne** [comment] 2016-05-12 07:09
You're probably missing 

```
  <repository>
            <id>neo4j-snapshots</id>
            <url>http://m2.neo4j.org/content/repositories/snapshots</url>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
```

I have it installed locally already. I'll create a new branch and push it a little later today, after a re-test.

**Comment by arafalov** [comment] 2016-05-18 10:26
I've re-downloaded project, added repository, changed version. It builds, runs and still gives an error:

> $ curl http://localhost:8080/graph
> {
>   "timestamp" : "2016-05-18T10:25:43.954+0000",
>   "status" : 500,
>   "error" : "Internal Server Error",
>   "exception" : "java.lang.ClassCastException",
>   "message" : "[Ljava.lang.String; cannot be cast to java.util.Collection",
>   "path" : "/graph"
> }

**Comment by pdtyreus** [comment] 2016-06-01 04:41
I'm pretty sure I see where this error is coming from. I think (based on the tests I just wrote), if you change [this line](https://github.com/neo4j-examples/movies-java-spring-data-neo4j-4/blob/master/src/main/java/movies/spring/data/neo4j/services/MovieService.java#L26) of MovieService to

``` java
for (String name : (String []) row.get("cast")) {
```

it will work. I don't have time to test right now, but if I get a minute tomorrow I will try it and submit a PR.

**Comment by ishepherd** [comment] 2016-06-07 11:33
Running Neo4J Server 3.0.1.
I have applied all the suggestions here so far [#1](https://github.com/neo4j-examples/movies-java-spring-data-neo4j-4/issues/3#issuecomment-218655330) [#2](https://github.com/neo4j-examples/movies-java-spring-data-neo4j-4/issues/3#issuecomment-218677437) [#3](https://github.com/neo4j-examples/movies-java-spring-data-neo4j-4/issues/3#issuecomment-222890981).

It will now draw the first page but with a blizzard of errors
The first is

```
2016-06-07 21:29:59,976  WARN .support.DefaultHandlerExceptionResolver: 400 - Failed to write HTTP message: org.springframework.http.converter.HttpMessageNotWritableException: Could not write content: Can not start an object, expecting field name; nested exception is com.fasterxml.jackson.core.JsonGenerationException: Can not start an object, expecting field name
2016-06-07 21:29:59,986  WARN        org.eclipse.jetty.server.Response: 565 - Committed before 500 null
2016-06-07 21:29:59,991  WARN .support.DefaultHandlerExceptionResolver: 165 - Handling of [org.springframework.http.converter.HttpMessageNotWritableException] resulted in Exception
java.lang.IllegalStateException: Committed
    at org.eclipse.jetty.server.Response.resetBuffer(Response.java:1243) ~[jetty-server-9.2.14.v20151106.jar:9.2.14.v20151106]
    at org.eclipse.jetty.server.Response.sendError(Response.java:567) ~[jetty-server-9.2.14.v20151106.jar:9.2.14.v20151106]
    at org.eclipse.jetty.server.Response.sendError(Response.java:544) ~[jetty-server-9.2.14.v20151106.jar:9.2.14.v20151106]
    at org.springframework.web.servlet.mvc.support.DefaultHandlerExceptionResolver.sendServerError(DefaultHandlerExceptionResolver.java:488) ~[spring-webmvc-4.2.3.RELEASE.jar:4.2.3.RELEASE]
    at org.springframework.web.servlet.mvc.support.DefaultHandlerExceptionResolver.handleHttpMessageNotWritable(DefaultHandlerExceptionResolver.java:402) ~[spring-webmvc-4.2.3.RELEASE.jar:4.2.3.RELEASE]
    at org.springframework.web.servlet.mvc.support.DefaultHandlerExceptionResolver.doResolveException(DefaultHandlerExceptionResolver.java:146) ~[spring-webmvc-4.2.3.RELEASE.jar:4.2.3.RELEASE]
    at org.springframework.web.servlet.handler.AbstractHandlerExceptionResolver.resolveException(AbstractHandlerExceptionResolver.java:137) [spring-webmvc-4.2.3.RELEASE.jar:4.2.3.RELEASE]
    at org.springframework.web.servlet.handler.HandlerExceptionResolverComposite.resolveException(HandlerExceptionResolverComposite.java:74) [spring-webmvc-4.2.3.RELEASE.jar:4.2.3.RELEASE]
    at org.springframework.web.servlet.DispatcherServlet.processHandlerException(DispatcherServlet.java:1183) [spring-webmvc-4.2.3.RELEASE.jar:4.2.3.RELEASE]
    at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1020) [spring-webmvc-4.2.3.RELEASE.jar:4.2.3.RELEASE]
    at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:971) [spring-webmvc-4.2.3.RELEASE.jar:4.2.3.RELEASE]
    at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893) [spring-webmvc-4.2.3.RELEASE.jar:4.2.3.RELEASE]
    at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970) [spring-webmvc-4.2.3.RELEASE.jar:4.2.3.RELEASE]
    at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861) [spring-webmvc-4.2.3.RELEASE.jar:4.2.3.RELEASE]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:622) [tomcat-embed-core-8.0.28.jar:8.0.28]
    at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846) [spring-webmvc-4.2.3.RELEASE.jar:4.2.3.RELEASE]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:729) [tomcat-embed-core-8.0.28.jar:8.0.28]
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812) [jetty-servlet-9.2.14.v20151106.jar:9.2.14.v20151106]
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669) [jetty-servlet-9.2.14.v20151106.jar:9.2.14.v20151106]
    at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99) [spring-web-4.2.3.RELEASE.jar:4.2.3.RELEASE]
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.2.3.RELEASE.jar:4.2.3.RELEASE]
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [jetty-servlet-9.2.14.v20151106.jar:9.2.14.v20151106]
    at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:87) [spring-web-4.2.3.RELEASE.jar:4.2.3.RELEASE]
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.2.3.RELEASE.jar:4.2.3.RELEASE]
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [jetty-servlet-9.2.14.v20151106.jar:9.2.14.v20151106]
    at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:77) [spring-web-4.2.3.RELEASE.jar:4.2.3.RELEASE]
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.2.3.RELEASE.jar:4.2.3.RELEASE]
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [jetty-servlet-9.2.14.v20151106.jar:9.2.14.v20151106]
    at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:121) [spring-web-4.2.3.RELEASE.jar:4.2.3.RELEASE]
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.2.3.RELEASE.jar:4.2.3.RELEASE]
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [jetty-servlet-9.2.14.v20151106.jar:9.2.14.v20151106]
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585) [jetty-servlet-9.2.14.v20151106.jar:9.2.14.v20151106]
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) [jetty-server-9.2.14.v20151106.jar:9.2.14.v20151106]
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577) [jetty-security-9.2.14.v20151106.jar:9.2.14.v20151106]
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223) [jetty-server-9.2.14.v20151106.jar:9.2.14.v20151106]
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127) [jetty-server-9.2.14.v20151106.jar:9.2.14.v20151106]
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515) [jetty-servlet-9.2.14.v20151106.jar:9.2.14.v20151106]
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) [jetty-server-9.2.14.v20151106.jar:9.2.14.v20151106]
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061) [jetty-server-9.2.14.v20151106.jar:9.2.14.v20151106]
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.2.14.v20151106.jar:9.2.14.v20151106]
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [jetty-server-9.2.14.v20151106.jar:9.2.14.v20151106]
    at org.eclipse.jetty.server.Server.handle(Server.java:499) [jetty-server-9.2.14.v20151106.jar:9.2.14.v20151106]
    at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311) [jetty-server-9.2.14.v20151106.jar:9.2.14.v20151106]
    at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257) [jetty-server-9.2.14.v20151106.jar:9.2.14.v20151106]
    at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544) [jetty-io-9.2.14.v20151106.jar:9.2.14.v20151106]
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635) [jetty-util-9.2.14.v20151106.jar:9.2.14.v20151106]
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555) [jetty-util-9.2.14.v20151106.jar:9.2.14.v20151106]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
```

**Comment by ishepherd** [comment] 2016-06-07 12:00
Uninstalled Neo4J Server 3.0.1 - Installed version 2.3.4 instead, with an empty .graphdb.

Workarounds [#1](https://github.com/neo4j-examples/movies-java-spring-data-neo4j-4/issues/3#issuecomment-218655330) [#2](https://github.com/neo4j-examples/movies-java-spring-data-neo4j-4/issues/3#issuecomment-218677437) are no longer necessary. But [#3](https://github.com/neo4j-examples/movies-java-spring-data-neo4j-4/issues/3#issuecomment-222890981) still is and I get the same error as in my last comment above.

**Edit** Up to now, I've just been trying http://localhost:8080

If I try http://localhost:8080/movies/search/findByTitle?title=The%20Matrix, what seems to happen is the stream gets closed prematurely. Sometimes it'll manage to get ~200 bytes through before it closes so I see the start of a JSON doc. Other times nothing at all.
The console says

```
2016-06-07 22:06:24,922  WARN .support.DefaultHandlerExceptionResolver: 400 - Failed to write HTTP message: org.springframework.http.converter.HttpMessageNotWritableException: Could not write content: Can not start an object, expecting field name; nested exception is com.fasterxml.jackson.core.JsonGenerationException: Can not start an object, expecting field name
2016-06-07 22:06:24,922  WARN        org.eclipse.jetty.server.Response: 565 - Committed before 500 null
2016-06-07 22:06:24,923  WARN .support.DefaultHandlerExceptionResolver: 165 - Handling of [org.springframework.http.converter.HttpMessageNotWritableException] resulted in Exception
java.lang.IllegalStateException: Committed
    at org.eclipse.jetty.server.Response.resetBuffer(Response.java:1243) ~[jetty-server-9.2.14.v20151106.jar:9.2.14.v20151106]
```

(hundreds more lines like this)

**Comment by ishepherd** [comment] 2016-06-08 23:14
I am getting closer to the problem, I think. It is sending incorrect output through Jackson, multiple objects when one is expected, something like that.
@luanne Is it working for you?

**Comment by luanne** [comment] 2016-06-09 08:31
@ishepherd sorry, I will be able to look at this only next week

**Comment by luanne** [comment] 2016-06-15 07:37
@ishepherd I've just switched to Neo4j 2.3.3 and I'm able to see what you've reported with `http://localhost:8080/movies/search/findByTitle?title=The%20Matrix`. Looking into it.

**Comment by luanne** [comment] 2016-06-15 08:28
Looks like a Spring (Boot/Rest?) problem. I switched OGM drivers and verified that Neo4j sends the response correctly, but it's mangled by Spring thereafter. The closest I found was https://jira.spring.io/browse/DATAREST-697 but that's marked fixed, so, I'm not quite sure what this is at the moment :-(

**Comment by ishepherd** [comment] 2016-06-15 08:33
@luanne Thanks for looking. I gave up and tried the University example and I am having different problems over there :-S many thanks if you could look... https://github.com/neo4j-examples/neo4j-ogm-university/issues/8

**Comment by netrebel** [comment] 2016-09-15 18:35
I get the same error:

`
Caused by: org.springframework.http.converter.HttpMessageNotWritableException: Could not write content: Can not start an object, expecting field name; nested exception is com.fasterxml.jackson.core.JsonGenerationException: Can not start an object, expecting field name
`

Updated MovieService to have `String[]`: 
`for (Object name : (String[]) row.get("cast"))`

I'm using:

```
<neo4j.version>3.0.5</neo4j.version>
<spring-data-neo4j.version>4.1.2.RELEASE</spring-data-neo4j.version>
```

The application sort of works but the Exceptions are thrown when trying to get the data for movies. The JSON returned for movies is broken. See:

`GET http://localhost:8080/movies/search/findByTitle?title=The%20Matrix net::ERR_INCOMPLETE_CHUNKED_ENCODING`

```
{
  "@id" : "1",
  "title" : "The Matrix",
  "released" : 1999,
  "tagline" : "Welcome to the Real World",
  "roles" : [ {
    "@id" : "2",
    "roles" : [ "Neo" ],
    "person" : {
      "@id" : "3"
```

It's probably something with the`jackson-jsog` library when`spring-data-neo4j` is trying to serialize the `@NodeEntity` classes into Json. Somewhere deep in the code that implements the `GraphRepository`...

**Comment by mangrish** [comment] 2017-03-22 13:19
This should be fixed on master. If you are still having issues please reopen.

**Closed as completed by mangrish** 2017-03-22 13:19 UTC
